### ISSUE TITLE
Arduino UNO keeps restarting

### ISSUE THREAD

**Issue by epranka** [morcibacsi/arduino_tss463_van#4]
Hi, thanks for your awesome work on this library.

I am using the Arduino UNO, TSS463C + MCP2551. Read & Write works fine, but my Arduino Uno keeps restarting or hanging randomly. Can be a problem that my Arduino is not genuine? Or maybe memory issues?

**Comment by morcibacsi** [comment]
Without seeing some code it is quite hard to tell. I haven't tested the library extensively on Arduino boards (I am using ESP32 boards). But I would suspect that restarting issues are coming from the main sketch. Usually I advise to try to build your app from the bottom-up, and try testing after every major change thoroughly. Start with the bare minimum (for example just with reading the VAN bus). If that works reliably, try adding your next feature. If that also seems OK, move to the next. This way you can pinpoint what functionality causes the crash.
If you have a larger sketch, you also can go backwards: try commenting out features one by one, until it seems stable. This way the last removed feature will contain the bug which crashes your app.

Good luck.

**Comment by epranka** [comment]
Thanks for your response. I just bought genuine Arduino and all works fine. It was the memory issue with the Arduino clone.
